---
- name: Check if cups-browsed service is running
  hosts: prccnonprodservers
  remote_user: afernandez
  become: yes
  tasks:
    - name: Check the status of cups-browsed service
      ansible.builtin.systemd:
        name: cups-browsed
        state: started
      register: service_status
      ignore_errors: yes

    - name: Display service status
      debug:
        msg: >
          {% if service_status.failed is defined and service_status.failed %}
            cups-browsed service not found on this host.
          {% elif service_status.state is defined %}
            cups-browsed is {{ service_status.state }}
          {% else %}
            cups-browsed service status unknown.
          {% endif %}

    - name: Check if service is running or not
      fail:
        msg: "cups-browsed is not running."
      when: service_status.state is defined and service_status.state != "started"
